// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: posts_service.proto

package postspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPrivate     bool                   `protobuf:"varint,1,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_posts_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Post) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	AuthorId      int32                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostServiceInfo) Reset() {
	*x = PostServiceInfo{}
	mi := &file_posts_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostServiceInfo) ProtoMessage() {}

func (x *PostServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostServiceInfo.ProtoReflect.Descriptor instead.
func (*PostServiceInfo) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{1}
}

func (x *PostServiceInfo) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostServiceInfo) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PostServiceInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostServiceInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PostFullInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Details       *PostServiceInfo       `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostFullInfo) Reset() {
	*x = PostFullInfo{}
	mi := &file_posts_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostFullInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFullInfo) ProtoMessage() {}

func (x *PostFullInfo) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFullInfo.ProtoReflect.Descriptor instead.
func (*PostFullInfo) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{2}
}

func (x *PostFullInfo) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *PostFullInfo) GetDetails() *PostServiceInfo {
	if x != nil {
		return x.Details
	}
	return nil
}

type PostsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostsList     []*PostFullInfo        `protobuf:"bytes,1,rep,name=postsList,proto3" json:"postsList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostsList) Reset() {
	*x = PostsList{}
	mi := &file_posts_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsList) ProtoMessage() {}

func (x *PostsList) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsList.ProtoReflect.Descriptor instead.
func (*PostsList) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{3}
}

func (x *PostsList) GetPostsList() []*PostFullInfo {
	if x != nil {
		return x.PostsList
	}
	return nil
}

type AddPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostRequest) Reset() {
	*x = AddPostRequest{}
	mi := &file_posts_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostRequest) ProtoMessage() {}

func (x *AddPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostRequest.ProtoReflect.Descriptor instead.
func (*AddPostRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddPostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *AddPostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostResponse) Reset() {
	*x = AddPostResponse{}
	mi := &file_posts_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostResponse) ProtoMessage() {}

func (x *AddPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostResponse.ProtoReflect.Descriptor instead.
func (*AddPostResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{5}
}

func (x *AddPostResponse) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_posts_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetPostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostFullInfo          `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_posts_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostResponse) GetPost() *PostFullInfo {
	if x != nil {
		return x.Post
	}
	return nil
}

type GetAllPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostsPerPageN int32                  `protobuf:"varint,1,opt,name=postsPerPageN,proto3" json:"postsPerPageN,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsRequest) Reset() {
	*x = GetAllPostsRequest{}
	mi := &file_posts_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsRequest) ProtoMessage() {}

func (x *GetAllPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPostsRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllPostsRequest) GetPostsPerPageN() int32 {
	if x != nil {
		return x.PostsPerPageN
	}
	return 0
}

type GetAllPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostsList           `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsResponse) Reset() {
	*x = GetAllPostsResponse{}
	mi := &file_posts_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsResponse) ProtoMessage() {}

func (x *GetAllPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostsResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllPostsResponse) GetPosts() []*PostsList {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetAllPostsOfOneAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostsPerPageN int32                  `protobuf:"varint,2,opt,name=postsPerPageN,proto3" json:"postsPerPageN,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsOfOneAuthorRequest) Reset() {
	*x = GetAllPostsOfOneAuthorRequest{}
	mi := &file_posts_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsOfOneAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsOfOneAuthorRequest) ProtoMessage() {}

func (x *GetAllPostsOfOneAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsOfOneAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAllPostsOfOneAuthorRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllPostsOfOneAuthorRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAllPostsOfOneAuthorRequest) GetPostsPerPageN() int32 {
	if x != nil {
		return x.PostsPerPageN
	}
	return 0
}

type GetAllPostsOfOneAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostsList           `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsOfOneAuthorResponse) Reset() {
	*x = GetAllPostsOfOneAuthorResponse{}
	mi := &file_posts_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsOfOneAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsOfOneAuthorResponse) ProtoMessage() {}

func (x *GetAllPostsOfOneAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsOfOneAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostsOfOneAuthorResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllPostsOfOneAuthorResponse) GetPosts() []*PostsList {
	if x != nil {
		return x.Posts
	}
	return nil
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Post          *Post                  `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_posts_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UpdatePostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_posts_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{13}
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_posts_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeletePostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_posts_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{15}
}

var File_posts_service_proto protoreflect.FileDescriptor

const file_posts_service_proto_rawDesc = "" +
	"\n" +
	"\x13posts_service.proto\x12\x05posts\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x04Post\x12\x1c\n" +
	"\tisPrivate\x18\x01 \x01(\bR\tisPrivate\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\xbb\x01\n" +
	"\x0fPostServiceInfo\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x05R\x06postId\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x05R\bauthorId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"a\n" +
	"\fPostFullInfo\x12\x1f\n" +
	"\x04post\x18\x01 \x01(\v2\v.posts.PostR\x04post\x120\n" +
	"\adetails\x18\x02 \x01(\v2\x16.posts.PostServiceInfoR\adetails\">\n" +
	"\tPostsList\x121\n" +
	"\tpostsList\x18\x01 \x03(\v2\x13.posts.PostFullInfoR\tpostsList\"I\n" +
	"\x0eAddPostRequest\x12\x1f\n" +
	"\x04post\x18\x01 \x01(\v2\v.posts.PostR\x04post\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\")\n" +
	"\x0fAddPostResponse\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x05R\x06postId\"@\n" +
	"\x0eGetPostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x05R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\":\n" +
	"\x0fGetPostResponse\x12'\n" +
	"\x04post\x18\x01 \x01(\v2\x13.posts.PostFullInfoR\x04post\":\n" +
	"\x12GetAllPostsRequest\x12$\n" +
	"\rpostsPerPageN\x18\x01 \x01(\x05R\rpostsPerPageN\"=\n" +
	"\x13GetAllPostsResponse\x12&\n" +
	"\x05posts\x18\x01 \x03(\v2\x10.posts.PostsListR\x05posts\"]\n" +
	"\x1dGetAllPostsOfOneAuthorRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12$\n" +
	"\rpostsPerPageN\x18\x02 \x01(\x05R\rpostsPerPageN\"H\n" +
	"\x1eGetAllPostsOfOneAuthorResponse\x12&\n" +
	"\x05posts\x18\x01 \x03(\v2\x10.posts.PostsListR\x05posts\"d\n" +
	"\x11UpdatePostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x05R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\x04post\x18\x03 \x01(\v2\v.posts.PostR\x04post\"\x14\n" +
	"\x12UpdatePostResponse\"C\n" +
	"\x11DeletePostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x05R\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\"\x14\n" +
	"\x12DeletePostResponse2\xb5\x03\n" +
	"\fPostsService\x128\n" +
	"\aAddPost\x12\x15.posts.AddPostRequest\x1a\x16.posts.AddPostResponse\x128\n" +
	"\aGetPost\x12\x15.posts.GetPostRequest\x1a\x16.posts.GetPostResponse\x12D\n" +
	"\vGetAllPosts\x12\x19.posts.GetAllPostsRequest\x1a\x1a.posts.GetAllPostsResponse\x12e\n" +
	"\x16GetAllPostsOfOneAuthor\x12$.posts.GetAllPostsOfOneAuthorRequest\x1a%.posts.GetAllPostsOfOneAuthorResponse\x12A\n" +
	"\n" +
	"UpdatePost\x12\x18.posts.UpdatePostRequest\x1a\x19.posts.UpdatePostResponse\x12A\n" +
	"\n" +
	"DeletePost\x12\x18.posts.DeletePostRequest\x1a\x19.posts.DeletePostResponseB9Z7github.com/LeonidS635/soa/internal/pkg/services/postspbb\x06proto3"

var (
	file_posts_service_proto_rawDescOnce sync.Once
	file_posts_service_proto_rawDescData []byte
)

func file_posts_service_proto_rawDescGZIP() []byte {
	file_posts_service_proto_rawDescOnce.Do(func() {
		file_posts_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_service_proto_rawDesc), len(file_posts_service_proto_rawDesc)))
	})
	return file_posts_service_proto_rawDescData
}

var file_posts_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_posts_service_proto_goTypes = []any{
	(*Post)(nil),                           // 0: posts.Post
	(*PostServiceInfo)(nil),                // 1: posts.PostServiceInfo
	(*PostFullInfo)(nil),                   // 2: posts.PostFullInfo
	(*PostsList)(nil),                      // 3: posts.PostsList
	(*AddPostRequest)(nil),                 // 4: posts.AddPostRequest
	(*AddPostResponse)(nil),                // 5: posts.AddPostResponse
	(*GetPostRequest)(nil),                 // 6: posts.GetPostRequest
	(*GetPostResponse)(nil),                // 7: posts.GetPostResponse
	(*GetAllPostsRequest)(nil),             // 8: posts.GetAllPostsRequest
	(*GetAllPostsResponse)(nil),            // 9: posts.GetAllPostsResponse
	(*GetAllPostsOfOneAuthorRequest)(nil),  // 10: posts.GetAllPostsOfOneAuthorRequest
	(*GetAllPostsOfOneAuthorResponse)(nil), // 11: posts.GetAllPostsOfOneAuthorResponse
	(*UpdatePostRequest)(nil),              // 12: posts.UpdatePostRequest
	(*UpdatePostResponse)(nil),             // 13: posts.UpdatePostResponse
	(*DeletePostRequest)(nil),              // 14: posts.DeletePostRequest
	(*DeletePostResponse)(nil),             // 15: posts.DeletePostResponse
	(*timestamppb.Timestamp)(nil),          // 16: google.protobuf.Timestamp
}
var file_posts_service_proto_depIdxs = []int32{
	16, // 0: posts.PostServiceInfo.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: posts.PostServiceInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: posts.PostFullInfo.post:type_name -> posts.Post
	1,  // 3: posts.PostFullInfo.details:type_name -> posts.PostServiceInfo
	2,  // 4: posts.PostsList.postsList:type_name -> posts.PostFullInfo
	0,  // 5: posts.AddPostRequest.post:type_name -> posts.Post
	2,  // 6: posts.GetPostResponse.post:type_name -> posts.PostFullInfo
	3,  // 7: posts.GetAllPostsResponse.posts:type_name -> posts.PostsList
	3,  // 8: posts.GetAllPostsOfOneAuthorResponse.posts:type_name -> posts.PostsList
	0,  // 9: posts.UpdatePostRequest.post:type_name -> posts.Post
	4,  // 10: posts.PostsService.AddPost:input_type -> posts.AddPostRequest
	6,  // 11: posts.PostsService.GetPost:input_type -> posts.GetPostRequest
	8,  // 12: posts.PostsService.GetAllPosts:input_type -> posts.GetAllPostsRequest
	10, // 13: posts.PostsService.GetAllPostsOfOneAuthor:input_type -> posts.GetAllPostsOfOneAuthorRequest
	12, // 14: posts.PostsService.UpdatePost:input_type -> posts.UpdatePostRequest
	14, // 15: posts.PostsService.DeletePost:input_type -> posts.DeletePostRequest
	5,  // 16: posts.PostsService.AddPost:output_type -> posts.AddPostResponse
	7,  // 17: posts.PostsService.GetPost:output_type -> posts.GetPostResponse
	9,  // 18: posts.PostsService.GetAllPosts:output_type -> posts.GetAllPostsResponse
	11, // 19: posts.PostsService.GetAllPostsOfOneAuthor:output_type -> posts.GetAllPostsOfOneAuthorResponse
	13, // 20: posts.PostsService.UpdatePost:output_type -> posts.UpdatePostResponse
	15, // 21: posts.PostsService.DeletePost:output_type -> posts.DeletePostResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_posts_service_proto_init() }
func file_posts_service_proto_init() {
	if File_posts_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_service_proto_rawDesc), len(file_posts_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_posts_service_proto_goTypes,
		DependencyIndexes: file_posts_service_proto_depIdxs,
		MessageInfos:      file_posts_service_proto_msgTypes,
	}.Build()
	File_posts_service_proto = out.File
	file_posts_service_proto_goTypes = nil
	file_posts_service_proto_depIdxs = nil
}
