// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: posts_service.proto

package postspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPrivate     bool                   `protobuf:"varint,1,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_posts_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Post) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId      int32                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostServiceInfo) Reset() {
	*x = PostServiceInfo{}
	mi := &file_posts_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostServiceInfo) ProtoMessage() {}

func (x *PostServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostServiceInfo.ProtoReflect.Descriptor instead.
func (*PostServiceInfo) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{1}
}

func (x *PostServiceInfo) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostServiceInfo) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PostServiceInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostServiceInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PostFullInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Details       *PostServiceInfo       `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostFullInfo) Reset() {
	*x = PostFullInfo{}
	mi := &file_posts_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostFullInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFullInfo) ProtoMessage() {}

func (x *PostFullInfo) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFullInfo.ProtoReflect.Descriptor instead.
func (*PostFullInfo) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{2}
}

func (x *PostFullInfo) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *PostFullInfo) GetDetails() *PostServiceInfo {
	if x != nil {
		return x.Details
	}
	return nil
}

type AddPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostRequest) Reset() {
	*x = AddPostRequest{}
	mi := &file_posts_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostRequest) ProtoMessage() {}

func (x *AddPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostRequest.ProtoReflect.Descriptor instead.
func (*AddPostRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddPostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *AddPostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostResponse) Reset() {
	*x = AddPostResponse{}
	mi := &file_posts_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostResponse) ProtoMessage() {}

func (x *AddPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostResponse.ProtoReflect.Descriptor instead.
func (*AddPostResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddPostResponse) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_posts_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetPostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostFullInfo          `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_posts_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetPostResponse) GetPost() *PostFullInfo {
	if x != nil {
		return x.Post
	}
	return nil
}

type GetAllPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsRequest) Reset() {
	*x = GetAllPostsRequest{}
	mi := &file_posts_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsRequest) ProtoMessage() {}

func (x *GetAllPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPostsRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetAllPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostFullInfo        `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsResponse) Reset() {
	*x = GetAllPostsResponse{}
	mi := &file_posts_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsResponse) ProtoMessage() {}

func (x *GetAllPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostsResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllPostsResponse) GetPosts() []*PostFullInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetAllMyPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMyPostsRequest) Reset() {
	*x = GetAllMyPostsRequest{}
	mi := &file_posts_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMyPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMyPostsRequest) ProtoMessage() {}

func (x *GetAllMyPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMyPostsRequest.ProtoReflect.Descriptor instead.
func (*GetAllMyPostsRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllMyPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllMyPostsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAllMyPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostFullInfo        `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMyPostsResponse) Reset() {
	*x = GetAllMyPostsResponse{}
	mi := &file_posts_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMyPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMyPostsResponse) ProtoMessage() {}

func (x *GetAllMyPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMyPostsResponse.ProtoReflect.Descriptor instead.
func (*GetAllMyPostsResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllMyPostsResponse) GetPosts() []*PostFullInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Post          *Post                  `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_posts_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UpdatePostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_posts_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{12}
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_posts_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeletePostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeletePostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_posts_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_posts_service_proto_rawDescGZIP(), []int{14}
}

var File_posts_service_proto protoreflect.FileDescriptor

const file_posts_service_proto_rawDesc = "" +
	"\n" +
	"\x13posts_service.proto\x12\x05posts\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x04Post\x12\x1d\n" +
	"\n" +
	"is_private\x18\x01 \x01(\bR\tisPrivate\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\xbd\x01\n" +
	"\x0fPostServiceInfo\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x05R\bauthorId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"a\n" +
	"\fPostFullInfo\x12\x1f\n" +
	"\x04post\x18\x01 \x01(\v2\v.posts.PostR\x04post\x120\n" +
	"\adetails\x18\x02 \x01(\v2\x16.posts.PostServiceInfoR\adetails\"J\n" +
	"\x0eAddPostRequest\x12\x1f\n" +
	"\x04post\x18\x01 \x01(\v2\v.posts.PostR\x04post\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"*\n" +
	"\x0fAddPostResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\"B\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\":\n" +
	"\x0fGetPostResponse\x12'\n" +
	"\x04post\x18\x01 \x01(\v2\x13.posts.PostFullInfoR\x04post\"(\n" +
	"\x12GetAllPostsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\"@\n" +
	"\x13GetAllPostsResponse\x12)\n" +
	"\x05posts\x18\x01 \x03(\v2\x13.posts.PostFullInfoR\x05posts\"C\n" +
	"\x14GetAllMyPostsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"B\n" +
	"\x15GetAllMyPostsResponse\x12)\n" +
	"\x05posts\x18\x01 \x03(\v2\x13.posts.PostFullInfoR\x05posts\"f\n" +
	"\x11UpdatePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\x04post\x18\x03 \x01(\v2\v.posts.PostR\x04post\"\x14\n" +
	"\x12UpdatePostResponse\"E\n" +
	"\x11DeletePostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"\x14\n" +
	"\x12DeletePostResponse2\x9a\x03\n" +
	"\fPostsService\x128\n" +
	"\aAddPost\x12\x15.posts.AddPostRequest\x1a\x16.posts.AddPostResponse\x128\n" +
	"\aGetPost\x12\x15.posts.GetPostRequest\x1a\x16.posts.GetPostResponse\x12D\n" +
	"\vGetAllPosts\x12\x19.posts.GetAllPostsRequest\x1a\x1a.posts.GetAllPostsResponse\x12J\n" +
	"\rGetAllMyPosts\x12\x1b.posts.GetAllMyPostsRequest\x1a\x1c.posts.GetAllMyPostsResponse\x12A\n" +
	"\n" +
	"UpdatePost\x12\x18.posts.UpdatePostRequest\x1a\x19.posts.UpdatePostResponse\x12A\n" +
	"\n" +
	"DeletePost\x12\x18.posts.DeletePostRequest\x1a\x19.posts.DeletePostResponseB9Z7github.com/LeonidS635/soa/internal/pkg/services/postspbb\x06proto3"

var (
	file_posts_service_proto_rawDescOnce sync.Once
	file_posts_service_proto_rawDescData []byte
)

func file_posts_service_proto_rawDescGZIP() []byte {
	file_posts_service_proto_rawDescOnce.Do(func() {
		file_posts_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_service_proto_rawDesc), len(file_posts_service_proto_rawDesc)))
	})
	return file_posts_service_proto_rawDescData
}

var file_posts_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_posts_service_proto_goTypes = []any{
	(*Post)(nil),                  // 0: posts.Post
	(*PostServiceInfo)(nil),       // 1: posts.PostServiceInfo
	(*PostFullInfo)(nil),          // 2: posts.PostFullInfo
	(*AddPostRequest)(nil),        // 3: posts.AddPostRequest
	(*AddPostResponse)(nil),       // 4: posts.AddPostResponse
	(*GetPostRequest)(nil),        // 5: posts.GetPostRequest
	(*GetPostResponse)(nil),       // 6: posts.GetPostResponse
	(*GetAllPostsRequest)(nil),    // 7: posts.GetAllPostsRequest
	(*GetAllPostsResponse)(nil),   // 8: posts.GetAllPostsResponse
	(*GetAllMyPostsRequest)(nil),  // 9: posts.GetAllMyPostsRequest
	(*GetAllMyPostsResponse)(nil), // 10: posts.GetAllMyPostsResponse
	(*UpdatePostRequest)(nil),     // 11: posts.UpdatePostRequest
	(*UpdatePostResponse)(nil),    // 12: posts.UpdatePostResponse
	(*DeletePostRequest)(nil),     // 13: posts.DeletePostRequest
	(*DeletePostResponse)(nil),    // 14: posts.DeletePostResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_posts_service_proto_depIdxs = []int32{
	15, // 0: posts.PostServiceInfo.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: posts.PostServiceInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: posts.PostFullInfo.post:type_name -> posts.Post
	1,  // 3: posts.PostFullInfo.details:type_name -> posts.PostServiceInfo
	0,  // 4: posts.AddPostRequest.post:type_name -> posts.Post
	2,  // 5: posts.GetPostResponse.post:type_name -> posts.PostFullInfo
	2,  // 6: posts.GetAllPostsResponse.posts:type_name -> posts.PostFullInfo
	2,  // 7: posts.GetAllMyPostsResponse.posts:type_name -> posts.PostFullInfo
	0,  // 8: posts.UpdatePostRequest.post:type_name -> posts.Post
	3,  // 9: posts.PostsService.AddPost:input_type -> posts.AddPostRequest
	5,  // 10: posts.PostsService.GetPost:input_type -> posts.GetPostRequest
	7,  // 11: posts.PostsService.GetAllPosts:input_type -> posts.GetAllPostsRequest
	9,  // 12: posts.PostsService.GetAllMyPosts:input_type -> posts.GetAllMyPostsRequest
	11, // 13: posts.PostsService.UpdatePost:input_type -> posts.UpdatePostRequest
	13, // 14: posts.PostsService.DeletePost:input_type -> posts.DeletePostRequest
	4,  // 15: posts.PostsService.AddPost:output_type -> posts.AddPostResponse
	6,  // 16: posts.PostsService.GetPost:output_type -> posts.GetPostResponse
	8,  // 17: posts.PostsService.GetAllPosts:output_type -> posts.GetAllPostsResponse
	10, // 18: posts.PostsService.GetAllMyPosts:output_type -> posts.GetAllMyPostsResponse
	12, // 19: posts.PostsService.UpdatePost:output_type -> posts.UpdatePostResponse
	14, // 20: posts.PostsService.DeletePost:output_type -> posts.DeletePostResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_posts_service_proto_init() }
func file_posts_service_proto_init() {
	if File_posts_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_service_proto_rawDesc), len(file_posts_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_posts_service_proto_goTypes,
		DependencyIndexes: file_posts_service_proto_depIdxs,
		MessageInfos:      file_posts_service_proto_msgTypes,
	}.Build()
	File_posts_service_proto = out.File
	file_posts_service_proto_goTypes = nil
	file_posts_service_proto_depIdxs = nil
}
