services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgesql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8090:8080"
    restart: always
    volumes:
      - ./configs/openapi.yaml:/configs/openapi.yaml
    environment:
      - SWAGGER_JSON=/configs/openapi.yaml
    container_name: swagger_ui

  api_gateway:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8081:8081"
    container_name: api_gateway

  user_service:
    build:
      context: .
      dockerfile: internal/services/user/Dockerfile
    ports:
      - "8082:8082"
    container_name: user_service