openapi: 3.0.3
info:
  title: Social Network API
  description: API социальной сети
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Локальный сервер разработки

paths:
  /signup:
    post:
      summary: Регистрация пользователя
      description: Создаёт нового пользователя и возвращает JWT-токен в cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password, email]
              properties:
                username:
                  type: string
                  example: "john_doe"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
                email:
                  type: string
                  format: email
                  example: "john@example.com"
      responses:
        "201":
          description: Успешная регистрация
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "jwt=jwt_token_here"
        "400":
          description: Ошибка валидации
        "409":
          description: Пользователь уже существует
        "500":
          description: Ошибка на стороне сервера

  /signin:
    post:
      summary: Вход в систему
      description: Аутентифицирует пользователя и возвращает JWT-токен в cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                  example: "john_doe"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        "200":
          description: Успешный вход
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "token=jwt_token_here; HttpOnly; Secure"
        "400":
          description: Ошибка валидации
        "403":
          description: Неверные учетные данные
        "500":
          description: Ошибка на стороне сервера

  /profile:
    get:
      summary: Получение профиля пользователя
      description: Возвращает данные профиля пользователя
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Успешное получение профиля
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "John"
                  surname:
                    type: string
                    example: "Doe"
                  age:
                    type: integer
                    example: 30
                  email:
                    type: string
                    format: email
                    example: "john@example.com"
                  phone:
                    type: string
                    format: phone
                    example: "1 (234) 567-89-00"
                  description:
                    type: string
                    example: "Software developer"
                  city:
                    type: string
                    example: "New York"
                  birthdate:
                    type: string
                    format: date
                    example: "2006-01-02T15:04:05Z"
        "400":
          description: JWT-токен отсутствует или невалиден
        "401":
          description: JWT-токен невалиден
        "403":
          description: Доступ запрещен
        "500":
          description: Ошибка на стороне сервера

    post:
      summary: Обновление профиля пользователя
      description: Позволяет пользователю обновить свои данные профиля
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John"
                surname:
                  type: string
                  example: "Doe"
                age:
                  type: integer
                  example: 30
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                phone:
                  type: string
                  format: phone
                  example: "1 (234) 567-89-00"
                description:
                  type: string
                  example: "Software developer"
                city:
                  type: string
                  example: "New York"
                birthdate:
                  type: string
                  format: date
                  example: "2006-01-02T15:04:05Z"
      responses:
        "200":
          description: Профиль успешно обновлён
        "400":
          description: JWT-токен отсутствует или невалиден, неверные данные профиля
        "401":
          description: JWT-токен невалиден
        "403":
          description: Доступ запрещен
        "500":
          description: Ошибка на стороне сервера

  /posts:
    post:
      summary: Публикация поста
      description: Публикует пост от имени пользователя
      security:
        - cookieAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_private:
                  type: boolean
                  example: false
                title:
                  type: string
                  example: "New post"
                tags:
                  type: array
                  items:
                    type: string
                  example: ["tag 1", "tag 2", "tag 3"]
                text:
                  type: string
                  example: "some very interesting text"
      responses:
        "200":
          description: Пост успешно опубликован
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: integer
                    example: 123
        "400":
          description: JWT-токен отсутствует или невалиден, неверные данные профиля
        "401":
          description: JWT-токен невалиден
        "403":
          description: Доступ запрещен
        "500":
          description: Ошибка на стороне сервера

  /posts/{id}:
    parameters:
      - name: id
        in: path
        description: ID поста
        schema:
          type: integer
          example: 123

    get:
      summary: Получение поста
      description: Возвращает данные поста
      security:
        - cookieAuth: [ ]
      responses:
        "200":
          description: Данные поста успешно переданы
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: integer
                    example: 123
                  user_id:
                    type: integer
                    example: 456
                  is_private:
                    type: boolean
                    example: false
                  title:
                    type: string
                    example: "New post"
                  tags:
                    type: array
                    items:
                      type: string
                    example: [ "tag 1", "tag 2", "tag 3" ]
                  text:
                    type: string
                    example: "some very interesting text"
                  created_at:
                    type: string
                    format: date
                    example: "2025-04-01T15:04:05Z"
                  updated_at:
                    type: string
                    format: date
                    example: "2025-04-01T21:14:34Z"
        "400":
          description: JWT-токен отсутствует или невалиден, неверные данные профиля
        "401":
          description: JWT-токен невалиден
        "403":
          description: Доступ запрещен
        "500":
          description: Ошибка на стороне сервера

    post:
      summary: Редактирование поста
      description: Обновляет данные поста
      security:
        - cookieAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_private:
                  type: boolean
                  example: false
                title:
                  type: string
                  example: "New post"
                tags:
                  type: array
                  items:
                    type: string
                  example: [ "tag 1", "tag 2", "tag 3" ]
                text:
                  type: string
                  example: "some very interesting text"
      responses:
        "200":
          description: Пост успешно обновлён
        "400":
          description: JWT-токен отсутствует или невалиден, неверные данные профиля
        "401":
          description: JWT-токен невалиден
        "403":
          description: Доступ запрещен
        "500":
          description: Ошибка на стороне сервера

    delete:
      summary: Удаление поста
      description: Удаляет данные поста
      security:
        - cookieAuth: [ ]
      responses:
        "200":
          description: Пост успешно удалён
        "400":
          description: JWT-токен отсутствует или невалиден, неверные данные профиля
        "401":
          description: JWT-токен невалиден
        "403":
          description: Доступ запрещен
        "500":
          description: Ошибка на стороне сервера

  /posts/all:
    get:
      summary: Получение всех постов
      description: Возвращает данные всех постов в виде пагинированного списка
      security:
        - cookieAuth: [ ]
      parameters:
        - name: page
          in: query
          description: Номер запрашиваемой страницы
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: Данные постов успешно переданы
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    post_id:
                      type: integer
                      example: 123
                    user_id:
                      type: integer
                      example: 456
                    is_private:
                      type: boolean
                      example: false
                    title:
                      type: string
                      example: "New post"
                    tags:
                      type: array
                      items:
                        type: string
                      example: [ "tag 1", "tag 2", "tag 3" ]
                    text:
                      type: string
                      example: "some very interesting text"
                    created_at:
                      type: string
                      format: date
                      example: "2025-04-01T15:04:05Z"
                    updated_at:
                      type: string
                      format: date
                      example: "2025-04-01T21:14:34Z"
        "400":
          description: JWT-токен отсутствует или невалиден, неверные данные профиля
        "401":
          description: JWT-токен невалиден
        "403":
          description: Доступ запрещен
        "500":
          description: Ошибка на стороне сервера

  /posts/all-mine:
    get:
      summary: Получение всех своих постов
      description: Возвращает данные всех постов одного автора в виде пагинированного списка
      security:
        - cookieAuth: [ ]
      parameters:
        - name: page
          in: query
          description: Номер запрашиваемой страницы
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: Данные постов успешно переданы
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    post_id:
                      type: integer
                      example: 123
                    user_id:
                      type: integer
                      example: 456
                    is_private:
                      type: boolean
                      example: false
                    title:
                      type: string
                      example: "New post"
                    tags:
                      type: array
                      items:
                        type: string
                      example: [ "tag 1", "tag 2", "tag 3" ]
                    text:
                      type: string
                      example: "some very interesting text"
                    created_at:
                      type: string
                      format: date
                      example: "2025-04-01T15:04:05Z"
                    updated_at:
                      type: string
                      format: date
                      example: "2025-04-01T21:14:34Z"
        "400":
          description: JWT-токен отсутствует или невалиден, неверные данные профиля
        "401":
          description: JWT-токен невалиден
        "403":
          description: Доступ запрещен
        "500":
          description: Ошибка на стороне сервера

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt